name: build-firmware
on: [push]

env:
  FIRMWARE_PATH: keyboards/bbrfkr/dynamis

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install qmk
      - run: qmk setup -y -H ../qmk_firmware
      - run: rm -rf ../qmk_firmware/$FIRMWARE_PATH
      - run: cp -r firmware/qmk/dynamis ../qmk_firmware/$FIRMWARE_PATH
      - run: >
          cd ../qmk_firmware &&
          qmk compile -kb bbrfkr/dynamis -km via &&
          cd - &&
          mkdir .artifacts &&
          cp ../qmk_firmware/.build/bbrfkr_dynamis_via.hex firmware/via/dynamis.json .artifacts
